spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

  config:
    import: configserver:http://localhost:8085

resilience4j:
  circuitbreaker:
    instances:

      productService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5

      paymentService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
server:
  port: 8082