spring:
  application:
    name: ms-product

  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  config:
    import: configserver:http://localhost:8085

server:
  port: 8081